theme = "tokyonight"

 [editor]
cursorline = true
color-modes = true
bufferline = "multiple"
soft-wrap.enable = true
gutters = ["diff", "diagnostics", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space]
space.q = ":quit"
space.s = ":w"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
Z = { Q = ":quit!", Z = ":write-quit!" }

[editor.statusline]
right = ["diagnostics", "selections", "position", "position-percentage"]

